-- @todo: replace the db name
USE "qlik_medical";

IF EXISTS (SELECT * FROM sysobjects WHERE name='F_PRESCRIBING' AND xtype='U')
  ALTER TABLE [dbo].[F_PRESCRIBING] DROP [F_PRESCRIBING_FK1];
  ALTER TABLE [dbo].[F_PRESCRIBING] DROP [F_PRESCRIBING_FK2];
  ALTER TABLE [dbo].[F_PRESCRIBING] DROP [F_PRESCRIBING_FK3];
  ALTER TABLE [dbo].[F_PRESCRIBING] DROP [F_PRESCRIBING_FK4];
  ALTER TABLE [dbo].[F_PRESCRIBING] DROP [F_PRESCRIBING_FK5];
  ALTER TABLE [dbo].[F_PRESCRIBING] DROP [F_PRESCRIBING_FK6];
  ALTER TABLE [dbo].[F_PRESCRIBING] DROP [F_PRESCRIBING_FK7];
GO

IF EXISTS (SELECT * FROM sysobjects WHERE name='D_PRACTICE' AND xtype='U')
  ALTER TABLE [dbo].[D_PRACTICE] DROP [D_PRACTICE_PK];
  ALTER TABLE [dbo].[D_PRACTICE] DROP [D_PRACTICE_FK1];
GO

IF EXISTS (SELECT * FROM sysobjects WHERE name='A_POSTCODE' AND xtype='U')
  ALTER TABLE [dbo].[A_POSTCODE] DROP [A_POSTCODE_PK];
  ALTER TABLE [dbo].[A_POSTCODE] DROP [A_POSTCODE_FK1];
GO

IF EXISTS (SELECT * FROM sysobjects WHERE name='A_LCG' AND xtype='U')
  ALTER TABLE [dbo].[A_LCG] DROP [A_LCG_PK];
GO

DROP TABLE [dbo].[A_LCG];
DROP TABLE [dbo].[D_AMP_NM];
DROP TABLE [dbo].[D_BNF];
DROP TABLE [dbo].[D_COST];
DROP TABLE [dbo].[D_TIME];
DROP TABLE [dbo].[D_VMP_NM];
DROP TABLE [dbo].[D_VTM_NM];
DROP TABLE [dbo].[F_PRESCRIBING];
DROP TABLE [dbo].[A_POSTCODE];
DROP TABLE [dbo].[D_PRACTICE];