-- @todo: replace the db name
USE "qlik_medical";

-- ALTER TABLE [dbo].[F_PRESCRIBING] DROP CONSTRAINT [F_PRESCRIBING_FK1];

-- ALTER TABLE [dbo].[D_AMP_NM] DROP CONSTRAINT [D_AMP_NM_PK];

--TRUNCATE TABLE [dbo].[D_AMP_NM];

ALTER TABLE [dbo].[D_AMP_NM] ADD  CONSTRAINT [D_AMP_NM_PK] PRIMARY KEY ("ID_AMP_NM");


ALTER TABLE [dbo].[F_PRESCRIBING] 
	ADD  CONSTRAINT [F_PRESCRIBING_FK1] 
		FOREIGN KEY([ID_AMP_NM]) REFERENCES [dbo].[D_AMP_NM] ([ID_AMP_NM]);


 