ALTER TABLE dbo.D_PRACTICE ADD 	
  CONSTRAINT D_PRACTICE_UNQ1 	UNIQUE( "ID_PRACTICE_ORG" );

ALTER TABLE [dbo].F_PRESCRIBING	ADD 
	CONSTRAINT F_PRESCRIBING_FK4 
		FOREIGN KEY ("ID_PRACTICE") REFERENCES [dbo].[D_PRACTICE]("ID_PRACTICE_ORG");