-- @todo: replace the db name
USE "qlik_medical";


-- Table: 
IF NOT EXISTS( SELECT * FROM sysobjects WHERE name='A_LCG' AND xtype='U' )
  CREATE TABLE "A_LCG"
  (
    "ID_LCG" INT NOT NULL,
    "LCG" VARCHAR(50)
    CONSTRAINT "A_LCG_PK" PRIMARY KEY ("ID_LCG")
  )
GO


-- Table: 
IF NOT EXISTS( SELECT * FROM sysobjects WHERE name='A_POSTCODE' AND xtype='U' )
  CREATE TABLE "A_POSTCODE"
  (
    "ID_POSTCODE" INT NOT NULL,
    "POSTCODE" VARCHAR(8),
    "ID_LCG" INT NOT NULL,
    CONSTRAINT "A_POSTCODE_PK" PRIMARY KEY ("ID_POSTCODE"),
    CONSTRAINT "A_POSTCODE_FK1" FOREIGN KEY ("ID_LCG") REFERENCES [dbo].[A_LCG]("ID_LCG") 
  )
GO


-- Table: 
IF NOT EXISTS( SELECT * FROM sysobjects WHERE name='D_AMP_NM' AND xtype='U' )
  CREATE TABLE "D_AMP_NM"
  (
    "ID_AMP_NM" INT NOT NULL,
    "AMP_NM" VARCHAR(200),
    "BNF_CODE" VARCHAR(15),
    "PRESENTATION" VARCHAR(50),
    "STRENGTH" VARCHAR(255),
    CONSTRAINT "D_AMP_NM_PK" PRIMARY KEY ("ID_AMP_NM")
  )
GO


-- Table: 
IF NOT EXISTS( SELECT * FROM sysobjects WHERE name='D_BNF' AND xtype='U' )
  CREATE TABLE "D_BNF"
  (
    "ID_BNF" INT NOT NULL ,
    "PARAGRAPH" VARCHAR(100),
    "SECTION" VARCHAR(100),
    "CHAPTER" VARCHAR(100),
    CONSTRAINT "D_BNF_PK" PRIMARY KEY ("ID_BNF")
  )
GO


-- Table: 
IF NOT EXISTS( SELECT * FROM sysobjects WHERE name='D_COST' AND xtype='U' )
  CREATE TABLE "D_COST"
  (
    "ID_INTERVAL_COST" INT NOT NULL ,
    "INTERVAL_COST" VARCHAR(20),
    CONSTRAINT "D_COST_PK" PRIMARY KEY ("ID_INTERVAL_COST")
  )
GO


-- Table: 
IF NOT EXISTS( SELECT * FROM sysobjects WHERE name='D_PRACTICE' AND xtype='U' )
  CREATE TABLE "D_PRACTICE"
  (
    "ID_PRACTICE" INT NOT NULL,
    "PRACTICENAME" VARCHAR(50),
    "ADDRESS1" VARCHAR(50),
    "ADDRESS2" VARCHAR(50),
    "ADDRESS3" VARCHAR(50),
    "ID_POSTCODE" INT NOT NULL,
    "ID_PRACTICE_ORG" INT NOT NULL,
    --@todo: add field patients
    CONSTRAINT "D_PRACTICE_PK" PRIMARY KEY ("ID_PRACTICE"),
    CONSTRAINT "D_PRACTICE_UNQ1" UNIQUE( "ID_PRACTICE_ORG" ),
    CONSTRAINT "D_PRACTICE_FK1" FOREIGN KEY ("ID_POSTCODE") REFERENCES [dbo].[A_POSTCODE]("ID_POSTCODE")
  )
GO


-- Table: 
IF NOT EXISTS( SELECT * FROM sysobjects WHERE name='D_TIME' AND xtype='U' )
  CREATE TABLE "D_TIME"
  (
    "ID_TIME" INT NOT NULL,
    "MONTH" INT NOT NULL,
    "YEAR" INT NOT NULL,
    CONSTRAINT "D_TIME_PK" PRIMARY KEY ("ID_TIME")
  )
GO


-- Table: 
IF NOT EXISTS( SELECT * FROM sysobjects WHERE name='D_VMP_NM' AND xtype='U' )
  CREATE TABLE "D_VMP_NM"
  (
    "ID_VMP_NM" INT NOT NULL,
    "VMP_NM" VARCHAR(220),
    CONSTRAINT "D_VMP_NM_PK" PRIMARY KEY ("ID_VMP_NM")
  )
GO


-- Table: 
IF NOT EXISTS( SELECT * FROM sysobjects WHERE name='D_VTM_NM' AND xtype='U' )
  CREATE TABLE "D_VTM_NM"
  (
    "ID_VTM_NM" INT NOT NULL,
    "VTM_NM" VARCHAR(100),
    CONSTRAINT "D_VTM_NM_PK" PRIMARY KEY ("ID_VTM_NM")
  )
GO


-- Table: 
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='F_PRESCRIBING' AND xtype='U')
  CREATE TABLE "F_PRESCRIBING"
  (
    "ID_AMP_NM" INT,
    "ID_VMP_NM" INT,
    "ID_VTM_NM" INT,
    "ID_INTERVAL_COST" INT,
    "ID_BNF" INT,
    "ID_PRACTICE" INT,
    "ID_TIME" INT,
    "TOTAL_ITEMS" INT,
    "TOTAL_QUANTITY" INT,
    "GROSS_COST" decimal(18,3),
    "ACTUAL_COST" decimal(18,3),
    CONSTRAINT "F_PRESCRIBING_FK1" FOREIGN KEY ("ID_AMP_NM") REFERENCES [dbo].[D_AMP_NM]("ID_AMP_NM") ,
    CONSTRAINT "F_PRESCRIBING_FK2" FOREIGN KEY ("ID_BNF") REFERENCES [dbo].[D_BNF]("ID_BNF") ,
    CONSTRAINT "F_PRESCRIBING_FK3" FOREIGN KEY	("ID_INTERVAL_COST") REFERENCES [dbo].[D_COST]("ID_INTERVAL_COST") ,
    CONSTRAINT "F_PRESCRIBING_FK5" FOREIGN KEY ("ID_TIME")	REFERENCES [dbo].[D_TIME]("ID_TIME") ,
    CONSTRAINT "F_PRESCRIBING_FK6" FOREIGN KEY ("ID_VMP_NM") REFERENCES [dbo].[D_VMP_NM]("ID_VMP_NM") ,
    CONSTRAINT "F_PRESCRIBING_FK7" FOREIGN KEY ("ID_VTM_NM") REFERENCES [dbo].[D_VTM_NM]("ID_VTM_NM") 
  )
GO
